version: "3.8"

services:
  api-docker:
    build:
      context: ./app
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
        DOCKER_GID: "${DOCKER_GID}"
    image: my-api-docker
    container_name: api-docker
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
      - SSL_CERT_PATH=/certs/docky.crt
      - SSL_KEY_PATH=/certs/docky.key
      # - MQTT_IP_BROKER=192.168.1.93
      # - MQTT_PORT_BROKER=${MQTT_PORT_BROKER}
      # - MQTT_USERNAME=${MQTT_USERNAME}
      # - MQTT_PASSWORD=${MQTT_PASSWORD}
      # - MQTT_TOPIC=${MQTT_TOPIC}
    volumes:
      - ./certs:/certs
      - ./app:/app
      - ~/.ssh/api-docker-key:/tmp/ssh/id_rsa:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5002:5002"
